version: '2'
services:
  myapp_php:
    build: .
    container_name: myapp_php
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:rw
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_ADDON_DB=my_database
      - MYSQL_ADDON_HOST=db
      - MYSQL_ADDON_USER=root
      - MYSQL_ADDON_PASSWORD=password
      - AUTH_KEY=''
      - SECURE_AUTH_KEY=''
      - LOGGED_IN_KEY=''
      - NONCE_KEY=''
      - AUTH_SALT=''
      - SECURE_AUTH_SALT=''
      - LOGGED_IN_SALT=''
      - NONCE_SALT=''
    networks:
      - front
      - back
  db:
    image: mariadb:10
    container_name: myapp_mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - back
networks:
  front: 
  back:
